# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CORENAME: wasm4
    CORE_ARGS: -DCMAKE_BUILD_TYPE=Release -DLIBRETRO=ON
    CMAKE_SOURCE_ROOT: runtimes/native

.core-defs-linux:
  extends: .core-defs
  variables:
    CORE_ARGS: -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release

.core-defs-osx:
  extends: .core-defs
  variables:
    CORE_ARGS: -G Xcode -DCMAKE_BUILD_TYPE=Release
    EXTRA_PATH: Release

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-cmake-mingw.yml'

  # DJGPP
  - project: 'libretro-infrastructure/ci-templates'
    file: '/djgpp-static-cmake.yml'

  # MacOS
  - project: 'libretro-infrastructure/ci-templates'
    file: 'osx-cmake.yml'

  # MacOS (PPC)
  - project: 'libretro-infrastructure/ci-templates'
    file: 'osx-cmake-ppc.yml'

  # Linux
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-cmake.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-cmake.yml'

  # iOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-cmake.yml'

  ################################## CONSOLES ################################
  # Libnx
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static-cmake.yml' 

  # CTR (3DS)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ctr-static-cmake.yml' 

  # PSP
  - project: 'libretro-infrastructure/ci-templates'
    file: '/psp-static-cmake.yml'

  # PS2
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ps2-static-cmake.yml'

  # VITA
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static-cmake.yml'

  # Dingux
  - project: 'libretro-infrastructure/ci-templates'
    file: '/dingux-cmake.yml'

  # WiiU
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wiiu-static-cmake.yml'

  # Wii
  - project: 'libretro-infrastructure/ci-templates'
    file: '/wii-static-cmake.yml'

  # Gamecube
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ngc-static-cmake.yml'

  # tvOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/tvos-cmake.yml'

  ################################## MISC ####################################
  # Emscripten
  - project: 'libretro-infrastructure/ci-templates'
    file: '/emscripten-static-cmake.yml' 

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  extends:
    - .libretro-windows-cmake-x86_64
    - .core-defs

# Windows 32-bit
libretro-build-windows-i686:
  extends:
    - .libretro-windows-cmake-x86
    - .core-defs

# DJGPP
libretro-build-djgpp-i586:
  extends:
    - .libretro-djgpp-static-cmake-retroarch-master
    - .core-defs

# Linux 64-bit
libretro-build-linux-x64:
  extends:
    - .libretro-linux-cmake-x86_64
    - .core-defs-linux

# Linux 32-bit
libretro-build-linux-i686:
  extends:
    - .libretro-linux-cmake-x86
    - .core-defs-linux

# MacOS 32-bit
libretro-build-osx-x86:
  extends:
    - .libretro-osx-cmake-x86
    - .core-defs-osx

# MacOS 64-bit
libretro-build-osx-x64:
  extends:
    - .libretro-osx-cmake-x86_64
    - .core-defs-osx

# MacOS ARM64
libretro-build-osx-arm64:
  extends:
    - .libretro-osx-cmake-arm64
    - .core-defs-osx

# MacOS PPC
libretro-build-osx-ppc:
  extends:
    - .libretro-osx-cmake-ppc
    - .core-defs

################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  extends:
    - .libretro-android-cmake-armeabi-v7a
    - .core-defs

# Android ARMv8a
android-arm64-v8a:
  extends:
    - .libretro-android-cmake-arm64-v8a
    - .core-defs

# Android 64-bit x86
android-x86_64:
  extends:
    - .libretro-android-cmake-x86_64
    - .core-defs

# Android 32-bit x86
android-x86:
  extends:
    - .libretro-android-cmake-x86
    - .core-defs

# iOS arm64
libretro-build-ios-arm64:
  extends:
    - .libretro-ios-cmake-arm64
    - .core-defs

# iOS armv7
libretro-build-ios9:
  extends:
    - .libretro-ios-cmake-ios9
    - .core-defs

################################### CONSOLES #################################
# Libnx
libretro-build-libnx-aarch64:
  extends:
    - .libretro-libnx-static-cmake-retroarch-master
    - .core-defs

# CTR (3ds)
libretro-build-ctr:
  extends:
    - .libretro-ctr-static-cmake-retroarch-master
    - .core-defs

# PSP
libretro-build-psp:
  extends:
    - .libretro-psp-static-cmake-retroarch-master
    - .core-defs

# PS2
libretro-build-ps2:
  extends:
    - .libretro-ps2-static-cmake-retroarch-master
    - .core-defs

# Wii
libretro-build-wii:
  extends:
    - .libretro-wii-static-cmake-retroarch-master
    - .core-defs

# Gamecube
libretro-build-ngc:
  extends:
    - .libretro-ngc-static-cmake-retroarch-master
    - .core-defs

# VITA
libretro-build-vita:
  extends:
    - .libretro-vita-static-cmake-retroarch-master
    - .core-defs

# Dingux
libretro-build-dingux-mips32:
  extends:
    - .libretro-dingux-cmake-mips32
    - .core-defs

libretro-build-dingux-odbeta-mips32:
  extends:
    - .libretro-dingux-odbeta-cmake-mips32
    - .core-defs

libretro-build-rs90-odbeta-mips32:
  extends:
    - .libretro-rs90-odbeta-cmake-mips32
    - .core-defs

libretro-build-retrofw-mips32:
  extends:
    - .libretro-retrofw-odbeta-cmake-mips32
    - .core-defs

libretro-build-miyoo-arm32:
  extends:
    - .libretro-miyoo-cmake-arm32
    - .core-defs

# iOS arm64
libretro-build-tvos-arm64:
  extends:
    - .libretro-tvos-cmake-arm64
    - .core-defs

# WiiU
libretro-build-wiiu:
  extends:
    - .libretro-wiiu-static-cmake-retroarch-master
    - .core-defs

################################### MISC #####################################

# Emscripten
libretro-build-emscripten:
  extends:
    - .libretro-emscripten-static-cmake-retroarch-master
    - .core-defs
